# In _config.yml
title: FYS-STK Demo
author: Karl Henrik Fredly and Morten Hjort-Jensen
logo: 
html_baseurl: https://karlhenrik.github.io/FYS-STK-Sandbox/
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib