# In _config.yml
title: FYS-STK Demo
author: Karl Henrik Fredly and Morten Hjort-Jensen
logo: 
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib